# shock_calendar.py
# Master Event Calendar (1997–2025)
# - Calendar/data only
# - Strategy rules live in a separate file
# - ETF impact is directional only: positive / negative / neutral
# - Intended for the 3-ETF universe:
#     069500 (KODEX 200), 114260 (KODEX K-Bond), 153130 (KODEX Short-term Bond/Cash)

shock_calendar = {
    # -----------------------------
    # 1997–2002: Post-IMF & Global Shock Period
    # -----------------------------
    "1997-11-21": {
        "date": "1997-11-21",
        "region": "Korea",
        "event_name": "IMF Crisis",
        "news_keywords": ["IMF", "foreign exchange crisis", "Korea crisis", "구제금융", "외환위기"],
        "analyst_theme": "Post-IMF restructuring, economic shock, safety preference, capital preservation",
        "shock_type": "macro_crisis",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2001-09-11": {
        "date": "2001-09-11",
        "region": "US / Global",
        "event_name": "9/11 Terror Attacks",
        "news_keywords": ["9/11", "terror", "terror attack", "테러", "미국 테러"],
        "analyst_theme": "Global risk-off shock, flight to safety, equity selloff",
        "shock_type": "global_shock",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2002-05-31_to_2002-06-30": {
        "start_date": "2002-05-31",
        "end_date": "2002-06-30",
        "region": "Korea / Global",
        "event_name": "2002 World Cup",
        "news_keywords": ["World Cup", "2002", "월드컵", "붉은악마", "Korea-Japan World Cup"],
        "analyst_theme": "National sentiment boost, consumption sentiment improvement, domestic optimism",
        "shock_type": "sentiment_positive",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "positive", "114260": "neutral", "153130": "neutral"},
    },

    # -----------------------------
    # 2004–2011: Safety, Geopolitics & Global Shocks
    # -----------------------------
    "2004-12-26": {
        "date": "2004-12-26",
        "region": "Asia / Global",
        "event_name": "Indian Ocean Tsunami",
        "news_keywords": ["tsunami", "Indian Ocean", "지진해일", "쓰나미"],
        "analyst_theme": "Humanitarian disaster, regional risk sentiment deterioration, safety demand",
        "shock_type": "natural_disaster",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2008-09-15": {
        "date": "2008-09-15",
        "region": "US / Global",
        "event_name": "Lehman Brothers Collapse / Global Financial Crisis",
        "news_keywords": ["Lehman", "GFC", "global financial crisis", "리먼", "글로벌 금융위기"],
        "analyst_theme": "Systemic financial crisis, severe equity drawdown, strong defensive rotation",
        "shock_type": "systemic_crisis",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2010-03-26": {
        "date": "2010-03-26",
        "region": "Korea",
        "event_name": "Cheonan Sinking",
        "news_keywords": ["Cheonan", "sinking", "천안함", "안보", "군사긴장"],
        "analyst_theme": "Geopolitical security shock, short-term domestic risk aversion",
        "shock_type": "geopolitical_tension",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2010-11-11": {
        "date": "2010-11-11",
        "region": "Korea / Global",
        "event_name": "G20 Seoul Summit",
        "news_keywords": ["G20", "Seoul Summit", "G20 정상회의", "서울 G20"],
        "analyst_theme": "Institutional maturity, international visibility, confidence and prestige effect",
        "shock_type": "institutional_positive",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "positive", "114260": "neutral", "153130": "neutral"},
    },
    "2011-03-11": {
        "date": "2011-03-11",
        "region": "Japan / Global",
        "event_name": "Fukushima Nuclear Disaster",
        "news_keywords": ["Fukushima", "nuclear disaster", "후쿠시마", "원전사고", "지진"],
        "analyst_theme": "Regional disaster shock, supply chain disruption, safety demand",
        "shock_type": "natural_disaster",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2011-08-05": {
        "date": "2011-08-05",
        "region": "US / Global",
        "event_name": "US Credit Rating Downgrade",
        "news_keywords": ["S&P downgrade", "US credit downgrade", "미국 신용등급 강등"],
        "analyst_theme": "Global macro uncertainty, risk-off, bond preference",
        "shock_type": "macro_crisis",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },

    # -----------------------------
    # 2014–2017: Social Trust & Institutional Maturity
    # -----------------------------
    "2014-04-16": {
        "date": "2014-04-16",
        "region": "Korea",
        "event_name": "Sewol Ferry Tragedy",
        "news_keywords": ["Sewol", "ferry tragedy", "세월호", "참사", "사회적 충격"],
        "analyst_theme": "Social trust shock, national mourning, risk sentiment deterioration",
        "shock_type": "social_tragedy",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2015-05-20": {
        "date": "2015-05-20",
        "region": "Korea",
        "event_name": "MERS Outbreak",
        "news_keywords": ["MERS", "outbreak", "메르스", "감염병", "보건위기"],
        "analyst_theme": "Public health shock, consumption slowdown, defensive preference",
        "shock_type": "pandemic",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2016-07-08": {
        "date": "2016-07-08",
        "region": "Korea / China",
        "event_name": "THAAD Conflict",
        "news_keywords": ["THAAD", "사드", "China retaliation", "중국 보복", "한중 갈등"],
        "analyst_theme": "Diplomatic and trade tension, sector-specific pressure, uncertainty",
        "shock_type": "geopolitical_trade_conflict",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2016-12-09": {
        "date": "2016-12-09",
        "region": "Korea",
        "event_name": "Park Geun-hye Impeachment",
        "news_keywords": ["impeachment", "박근혜 탄핵", "국정농단", "정치불확실성"],
        "analyst_theme": "Political uncertainty, governance transition, short-term risk aversion",
        "shock_type": "political_event",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "neutral", "114260": "neutral", "153130": "neutral"},
    },

    # -----------------------------
    # 2018–2020: Peace, Supply Chain & Pandemic
    # -----------------------------
    "2018-02-09": {
        "date": "2018-02-09",
        "region": "Korea",
        "event_name": "Pyeongchang Winter Olympics",
        "news_keywords": ["Pyeongchang", "Olympics", "평창올림픽", "평화", "국가 이미지"],
        "analyst_theme": "Peace sentiment, national branding, temporary confidence uplift",
        "shock_type": "sentiment_positive",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "positive", "114260": "neutral", "153130": "neutral"},
    },
    "2019-07-01_to_2019-12-31": {
        "start_date": "2019-07-01",
        "end_date": "2019-12-31",
        "region": "Korea / Japan",
        "event_name": "Japan Export Restrictions",
        "news_keywords": ["Japan export restrictions", "수출규제", "화이트리스트", "소부장"],
        "analyst_theme": "Supply chain disruption, trade tension, domestic industrial resilience focus",
        "shock_type": "trade_conflict",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2020-01-20_to_2020-06-30": {
        "start_date": "2020-01-20",
        "end_date": "2020-06-30",
        "region": "Korea / Global",
        "event_name": "COVID-19 / K-Quarantine",
        "news_keywords": ["COVID-19", "coronavirus", "코로나", "K-방역", "pandemic"],
        "analyst_theme": "Pandemic shock, mobility collapse, defensive allocation, quarantine response",
        "shock_type": "pandemic",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },

    # -----------------------------
    # 2021–2025: War, High Rates & Tech Competition
    # -----------------------------
    "2021-09-01_to_2024-12-31": {
        "start_date": "2021-09-01",
        "end_date": "2024-12-31",
        "region": "China / Global",
        "event_name": "China Real Estate Crisis",
        "news_keywords": ["Evergrande", "China real estate", "중국 부동산", "부채위기"],
        "analyst_theme": "China slowdown, global risk sentiment pressure, spillover uncertainty",
        "shock_type": "macro_crisis",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2022-02-24": {
        "date": "2022-02-24",
        "region": "Europe / Global",
        "event_name": "Russia-Ukraine War",
        "news_keywords": ["Russia-Ukraine", "war", "러시아 우크라이나 전쟁", "지정학 리스크"],
        "analyst_theme": "Geopolitical shock, commodity inflation, risk-off, defensive demand",
        "shock_type": "geopolitical_war",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2022-03-16_to_2024-12-31": {
        "start_date": "2022-03-16",
        "end_date": "2024-12-31",
        "region": "US / Global",
        "event_name": "US Rate Hike Cycle",
        "news_keywords": ["Fed hike", "rate hike", "긴축", "금리인상", "연준"],
        "analyst_theme": "Monetary tightening, valuation compression, bond-price sensitivity, risk-off regime",
        "shock_type": "monetary_tightening",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2022-10-29": {
        "date": "2022-10-29",
        "region": "Korea",
        "event_name": "Itaewon Tragedy",
        "news_keywords": ["Itaewon", "tragedy", "이태원", "참사", "사회 충격"],
        "analyst_theme": "Social trauma, domestic sentiment shock, temporary risk aversion",
        "shock_type": "social_tragedy",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2023-01-01_to_2024-12-31": {
        "start_date": "2023-01-01",
        "end_date": "2024-12-31",
        "region": "Global / Korea",
        "event_name": "AI / Semiconductor Cycle",
        "news_keywords": ["AI", "semiconductor", "반도체", "엔비디아", "generative AI"],
        "analyst_theme": "Tech cycle upturn, AI-led growth, semiconductor strength, equity support",
        "shock_type": "tech_boom",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "positive", "114260": "neutral", "153130": "neutral"},
    },

    # -----------------------------
    # 2024–2025: Recent Events / New Shocks
    # -----------------------------
    "2024-04-10": {
        "date": "2024-04-10",
        "region": "Korea",
        "event_name": "2024 Korea General Election",
        "news_keywords": ["election", "총선", "국회의원 선거", "정치 일정", "policy uncertainty"],
        "analyst_theme": "Political event, policy expectation reset, short-term sector rotation",
        "shock_type": "political_event",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "neutral", "114260": "neutral", "153130": "neutral"},
    },
    "2024-07-13": {
        "date": "2024-07-13",
        "region": "US",
        "event_name": "Trump Assassination Attempt",
        "news_keywords": ["Trump", "assassination attempt", "미국 대선", "정치 리스크"],
        "analyst_theme": "US political shock, volatility spike, risk sentiment disturbance",
        "shock_type": "political_shock",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2024-07-19_to_2024-07-21": {
        "start_date": "2024-07-19",
        "end_date": "2024-07-21",
        "region": "Global",
        "event_name": "Global IT Outage / CrowdStrike Incident",
        "news_keywords": ["CrowdStrike", "IT outage", "global outage", "전산장애", "보안사고"],
        "analyst_theme": "Technology infrastructure shock, operational disruption, temporary risk aversion",
        "shock_type": "tech_operational_shock",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2024-08-05": {
        "date": "2024-08-05",
        "region": "Global",
        "event_name": "Global Equity Volatility Spike / Yen Carry Unwind",
        "news_keywords": ["volatility spike", "yen carry trade", "risk-off", "글로벌 변동성", "엔캐리 청산"],
        "analyst_theme": "Cross-asset de-risking, global volatility shock, defensive allocation",
        "shock_type": "market_volatility_shock",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2024-12-03": {
        "date": "2024-12-03",
        "region": "Korea",
        "event_name": "Korea Martial-Law Emergency Shock",
        "news_keywords": ["martial law", "비상계엄", "정치 충격", "헌정 위기"],
        "analyst_theme": "Domestic political shock, abrupt uncertainty, strong risk-off response",
        "shock_type": "political_shock",
        "reference_flag": True,
        "backtest_flag": True,
        "etf_impact": {"069500": "negative", "114260": "positive", "153130": "positive"},
    },
    "2025-01-01_to_2025-12-31": {
        "start_date": "2025-01-01",
        "end_date": "2025-12-31",
        "region": "Global / Korea",
        "event_name": "Ongoing AI, Rates, and Geopolitical Regime",
        "news_keywords": ["AI", "rates", "geopolitics", "inflation", "semiconductor"],
        "analyst_theme": "Higher-for-longer rates, AI leadership, geopolitical fragmentation, regime uncertainty",
        "shock_type": "regime_shift",
        "reference_flag": True,
        "backtest_flag": False,
        "etf_impact": {"069500": "neutral", "114260": "neutral", "153130": "neutral"},
    },
}

def get_shock_calendar():
    return shock_calendar
